<div id="siteWrapper">
    <main>
        <div class="main-content">
            <div class="calculator-wrap">
                <div class="calcualtor-heading">
                    <h4>Vælg vinduer du ønsker pudset</h4>
                    <p>Klik på "plus" for at lægge flere til og "minus" for at trække fra</p>
                </div>
                <div class="button-container">
                    <div class="modifier-buttons">
                        <div class="double-option">
                            <p>Indvendig og udvendig pudsning ?</p>
                            <div class="double-mod no" data-enabled="false">Nej</div>
                        </div>
                        <div class="double-option-2">
                            <p>Er der forsatsvinduer ?</p>
                            <div class="double-mod-2 no" data-enabled="0">Nej</div>
                        </div>
                    </div>
                    <div class="regular-butons">
                        <div class="existing-clipcard">
                            <p>Har allerede klippekort ?</p>
                            <div class="existing-clipcard-mod no" data-enabled="false">Nej</div>
                        </div>
                    </div>
                </div>
                <div class="window-wrap">
                    <div class="section double-sided">
                        <div class="section-heading">
                            <div class="arrow down"></div>
                            <div class="category-name">2 fags vinduer</div>
                        </div>
                        <div class="window-container">
                            <div class="window" data-window="9">
                                <div class="window-id">9</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral i"></div>
                                </div>
                            </div>
                            <div class="window" data-window="10">
                                <div class="window-id">10</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral j"></div>
                                </div>
                            </div>
                            <div class="window" data-window="11">
                                <div class="window-id">11</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral l"></div>
                                </div>
                            </div>
                            <div class="window" data-window="12">
                                <div class="window-id">12</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral m"></div>
                                </div>
                            </div>
                            <div class="window" data-window="7">
                                <div class="window-id">7</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral g"></div>
                                </div>
                            </div>
                            <div class="window" data-window="8">
                                <div class="window-id">8</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral h"></div>
                                </div>
                            </div>
                            <div class="window" data-window="29">
                                <div class="window-id">29</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zf"></div>
                                </div>
                            </div>
                            <div class="window" data-window="32">
                                <div class="window-id">32</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zi"></div>
                                </div>
                            </div>
                            <div class="window" data-window="38">
                                <div class="window-id">38</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zp"></div>
                                </div>
                            </div>
                            <div class="window" data-window="43">
                                <div class="window-id">43</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zv"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="26">
                                <div class="window-id">26</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zb"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="35">
                                <div class="window-id">35</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zm"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section single-sided">
                        <div class="section-heading closed">
                            <div class="arrow"></div>
                            <div class="category-name">1 fags vinduer</div>
                        </div>
                        <div class="window-container closed">
                            <div class="window" data-window="1">
                                <div class="window-id">1</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden">12</div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral a"></div>
                                </div>
                            </div>
                            <div class="window" data-window="2">
                                <div class="window-id">2</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral b"></div>
                                </div>
                            </div>
                            <div class="window" data-window="3">
                                <div class="window-id">3</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral c"></div>

                                </div>
                            </div>
                            <div class="window" data-window="4">
                                <div class="window-id">4</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral d"></div>
                                </div>
                            </div>
                            <div class="window" data-window="5">
                                <div class="window-id">5</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral e"></div>
                                </div>
                            </div>
                            <div class="window" data-window="6">
                                <div class="window-id">6</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral f"></div>
                                </div>
                            </div>
                            <div class="window" data-window="28">
                                <div class="window-id">28</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral ze"></div>
                                </div>
                            </div>
                            <div class="window" data-window="31">
                                <div class="window-id">31</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zh"></div>
                                </div>
                            </div>
                            <div class="window" data-window="37">
                                <div class="window-id">37</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zo"></div>
                                </div>
                            </div>
                            <div class="window" data-window="42">
                                <div class="window-id">42</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zt"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="25">
                                <div class="window-id">25</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral za"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="34">
                                <div class="window-id">34</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zl"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section triple-sided">
                        <div class="section-heading closed">
                            <div class="arrow"></div>
                            <div class="category-name">3 fags vinduer</div>
                        </div>
                        <div class="window-container closed">
                            <div class="window" data-window="13">
                                <div class="window-id">13</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral n"></div>
                                </div>
                            </div>
                            <div class="window" data-window="14">
                                <div class="window-id">14</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral o"></div>
                                </div>
                            </div>
                            <div class="window" data-window="15">
                                <div class="window-id">15</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral p"></div>
                                </div>
                            </div>
                            <div class="window" data-window="16">
                                <div class="window-id">16</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral q"></div>
                                </div>
                            </div>
                            <div class="window" data-window="17">
                                <div class="window-id">17</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral r"></div>
                                </div>
                            </div>
                            <div class="window" data-window="18">
                                <div class="window-id">18</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral s"></div>
                                </div>
                            </div>
                            <div class="window" data-window="20">
                                <div class="window-id">20</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral v"></div>
                                </div>
                            </div>
                            <div class="window" data-window="30">
                                <div class="window-id">30</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zg"></div>
                                </div>
                            </div>
                            <div class="window" data-window="33">
                                <div class="window-id">33</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zj"></div>
                                </div>
                            </div>
                            <div class="window" data-window="39">
                                <div class="window-id">39</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zq"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="27">
                                <div class="window-id">27</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zc"></div>
                                </div>
                            </div>
                            <div class="window small" data-window="36">
                                <div class="window-id">36</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zn"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section special-windows">
                        <div class="section-heading closed">
                            <div class="arrow"></div>
                            <div class="category-name">Speciel vinduer</div>
                        </div>
                        <div class="window-container closed">
                            <div class="window" data-window="19">
                                <div class="window-id">19</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral t"></div>
                                </div>
                            </div>
                            <div class="window" data-window="21">
                                <div class="window-id">21</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral x"></div>
                                </div>
                            </div>
                            <div class="window" data-window="22">
                                <div class="window-id">22</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral y"></div>
                                </div>
                            </div>
                            <div class="window" data-window="23">
                                <div class="window-id">23</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral z"></div>
                                </div>
                            </div>
                            <div class="window" data-window="24">
                                <div class="window-id">24</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zz"></div>
                                </div>
                            </div>
                            <div class="window" data-window="40">
                                <div class="window-id">40</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zr"></div>
                                </div>
                            </div>
                            <div class="window" data-window="41">
                                <div class="window-id">41</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zs"></div>
                                </div>
                            </div>
                            <div class="window" data-window="44">
                                <div class="window-id">44</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zw"></div>
                                </div>
                            </div>
                            <div class="window" data-window="45">
                                <div class="window-id">45</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zx"></div>
                                </div>
                            </div>
                            <div class="window" data-window="46">
                                <div class="window-id">46</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="image-holder">
                                    <div class="neutral zy"></div>
                                </div>
                            </div>
                            <div class="window" data-window="0">
                                <div class="window-id">0</div>
                                <div class="qty-mngmt">
                                    <div class="w-minus"></div>
                                    <div class="w-plus"></div>
                                    <div class="qty hidden"></div>
                                </div>
                                <div class="dimensions">
                                    <div class="text">Hvis du ikke kan finde dit vindue , skriv størrelsen nedenfor</div>
                                    <input id="special-width" class="width" type="number" placeholder="Bredde">
                                    <input id="special-height" class="height" type="number" placeholder="Højde">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="calcualtor-bottom">
                    <h4>Vælg vinduer for udregning af pris</h4>
                    <div class="price calculate">Beregn priset</div>
                    <div class="mods"> i prisen inkluderet: <br>  *klippekort</div>
                    <div class="stamp-container">
                        <img class="stamp" src="https://static1.squarespace.com/static/5a5eef3732601e33d9f54eb6/t/5b4e1f092b6a286f9682dc8b/1531846409902/stamp-v1.png" />
                        <div class="more-info">klik for mere info</div>
                        <div class="stamp-p">Bliv fast kunde og få specialt rabatter kun for 100,- kr -></div>
                        <div class="apply-stamp">
                            <div class="text">Ønsker du klippekort</div>
                            <div class="stamp-mod" data-enabled="1">Ja</div>
                        </div>
                    </div>
                    <p class="minutes"></p>
                    <p>Efter valg af vinduer, udfyld venligst bestillings formular</p>
                </div>
            </div>
        </div>
    </main>
</div>