<?php
/**
 * Created by PhpStorm.
 * User: DELL
 * Date: 16.07.2018
 * Time: 14:57
 */
?>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Patua+One" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/assets/css/calculator.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/local.css">
    <script src="/assets/js/calculator.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>